<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RuntimeException;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        if (! filter_var(
            env('FRESHMART_SEED_DEMO', app()->environment(['local', 'testing'])),
            FILTER_VALIDATE_BOOL,
        )) {
            return;
        }

        $this->seedEmployees();
        $this->seedSuppliers();
        $this->seedProducts();
        $this->seedAccounts();
        $this->seedAttendance();
        $this->seedRequestsAndPayroll();
    }

    private function seedEmployees(): void
    {
        $employees = [
            [
                'employee_no' => 'EMP-0001',
                'full_name' => 'Maria Santos',
                'position' => 'Senior Cashier',
                'department' => 'Operations',
                'email' => 'maria.santos@example.test',
                'phone' => '0917-555-0101',
                'hire_date' => '2024-03-15',
                'employment_status' => 'Active',
                'leave_balance' => 15,
                'hourly_rate' => 120,
                'basic_salary' => 20000,
                'emergency_contact_name' => 'Ramon Santos',
                'emergency_contact_phone' => '0917-555-0191',
                'pay_type' => 'Monthly',
            ],
            [
                'employee_no' => 'EMP-0002',
                'full_name' => 'Juan dela Cruz',
                'position' => 'Store Supervisor',
                'department' => 'Operations',
                'email' => 'juan.delacruz@example.test',
                'phone' => '0917-555-0102',
                'hire_date' => '2023-01-10',
                'employment_status' => 'Active',
                'leave_balance' => 12.5,
                'hourly_rate' => 180,
                'basic_salary' => 30000,
                'emergency_contact_name' => 'Elena dela Cruz',
                'emergency_contact_phone' => '0917-555-0192',
                'pay_type' => 'Monthly',
            ],
            [
                'employee_no' => 'EMP-0003',
                'full_name' => 'Leah Mendoza',
                'position' => 'Inventory Clerk',
                'department' => 'Inventory',
                'email' => 'leah.mendoza@example.test',
                'phone' => '0917-555-0103',
                'hire_date' => '2025-06-02',
                'employment_status' => 'Active',
                'leave_balance' => 10,
                'hourly_rate' => 135,
                'basic_salary' => 22000,
                'emergency_contact_name' => 'Paolo Mendoza',
                'emergency_contact_phone' => '0917-555-0193',
                'pay_type' => 'Monthly',
            ],
        ];

        foreach ($employees as $employee) {
            DB::table('employees')->updateOrInsert(
                ['employee_no' => $employee['employee_no']],
                $employee,
            );
        }
    }

    private function seedSuppliers(): void
    {
        $suppliers = [
            [
                'name' => 'Manila Fresh Produce Co.',
                'contact_person' => 'Ana Reyes',
                'phone' => '0917-100-2001',
                'email' => 'sales@manilafresh.example.test',
                'address' => 'Divisoria, Manila',
                'status' => 'Active',
            ],
            [
                'name' => 'Luzon Pantry Supplies',
                'contact_person' => 'Marco Villanueva',
                'phone' => '0917-100-2002',
                'email' => 'orders@luzonpantry.example.test',
                'address' => 'Quezon City, Metro Manila',
                'status' => 'Active',
            ],
            [
                'name' => 'Metro Beverage Distribution',
                'contact_person' => 'Joyce Lim',
                'phone' => '0917-100-2003',
                'email' => 'trade@metrobeverage.example.test',
                'address' => 'Pasig City, Metro Manila',
                'status' => 'Active',
            ],
            [
                'name' => 'Southern Luzon Dairy & Frozen Foods',
                'contact_person' => 'Carlo Bautista',
                'phone' => '0917-100-2004',
                'email' => 'orders@southernluzondairy.example.test',
                'address' => 'Santa Rosa, Laguna',
                'status' => 'Active',
            ],
            [
                'name' => 'Metro Household & Personal Care Supply',
                'contact_person' => 'Liza Navarro',
                'phone' => '0917-100-2005',
                'email' => 'sales@metrohousehold.example.test',
                'address' => 'Mandaluyong City, Metro Manila',
                'status' => 'Active',
            ],
            [
                'name' => 'Philippine Grocery Brands Trading',
                'contact_person' => 'Rafael Garcia',
                'phone' => '0917-100-2006',
                'email' => 'trade@phgrocerybrands.example.test',
                'address' => 'Marikina City, Metro Manila',
                'status' => 'Active',
            ],
        ];

        foreach ($suppliers as $supplier) {
            DB::table('suppliers')->updateOrInsert(
                ['name' => $supplier['name']],
                $supplier,
            );
        }
    }

    private function seedProducts(): void
    {
        $supplierIds = DB::table('suppliers')->pluck('id', 'name');
        // SKU prefixes: FRU- Fruits; VEG- Vegetables; BAK- Bakery;
        // PAN- Pantry, Rice & Grains; BEV- Beverages; CND- Canned Goods and Condiments;
        // SNK- Snacks; DAI- Dairy; FRZ- Frozen Goods; HSH- Household; PER- Personal Care.
        $products = [
            [
                'sku' => 'FRU-001',
                'name' => 'Banana (Lakatan)',
                'price' => 65,
                'category' => 'Fruits',
                'stock_quantity' => 50,
                'unit' => 'kg',
                'emoji' => '🍌',
                'cost_price' => 42.25,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 150,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRU-002',
                'name' => 'Mango (Ripe)',
                'price' => 150,
                'category' => 'Fruits',
                'stock_quantity' => 24,
                'unit' => 'kg',
                'emoji' => '🥭',
                'cost_price' => 97.50,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 60,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'VEG-001',
                'name' => 'Tomato',
                'price' => 60,
                'category' => 'Vegetables',
                'stock_quantity' => 30,
                'unit' => 'kg',
                'emoji' => '🍅',
                'cost_price' => 39,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 90,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'VEG-002',
                'name' => 'Carrot',
                'price' => 75,
                'category' => 'Vegetables',
                'stock_quantity' => 20,
                'unit' => 'kg',
                'emoji' => '🥕',
                'cost_price' => 48.75,
                'reorder_level' => 6,
                'min_stock' => 3,
                'max_stock' => 60,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BAK-001',
                'name' => 'White Bread',
                'price' => 52,
                'category' => 'Bakery',
                'stock_quantity' => 18,
                'unit' => 'loaf',
                'emoji' => '🍞',
                'cost_price' => 34,
                'reorder_level' => 6,
                'min_stock' => 3,
                'max_stock' => 50,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PAN-001',
                'name' => 'Premium Rice',
                'price' => 58,
                'category' => 'Pantry',
                'stock_quantity' => 100,
                'unit' => 'kg',
                'emoji' => '🍚',
                'cost_price' => 45,
                'reorder_level' => 25,
                'min_stock' => 10,
                'max_stock' => 250,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BEV-001',
                'name' => 'Bottled Water',
                'price' => 25,
                'category' => 'Beverages',
                'stock_quantity' => 72,
                'unit' => 'bottle',
                'emoji' => '💧',
                'cost_price' => 14,
                'reorder_level' => 20,
                'min_stock' => 10,
                'max_stock' => 180,
                'supplier_id' => $supplierIds['Metro Beverage Distribution'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BEV-002',
                'name' => 'Orange Juice',
                'price' => 90,
                'category' => 'Beverages',
                'stock_quantity' => 32,
                'unit' => 'bottle',
                'emoji' => '🧃',
                'cost_price' => 58,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 80,
                'supplier_id' => $supplierIds['Metro Beverage Distribution'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRU-003',
                'name' => 'Calamansi',
                'price' => 55,
                'category' => 'Fruits',
                'stock_quantity' => 35,
                'unit' => 'kg',
                'emoji' => '🍋',
                'cost_price' => 35.75,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 100,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRU-004',
                'name' => 'Pineapple',
                'price' => 95,
                'category' => 'Fruits',
                'stock_quantity' => 28,
                'unit' => 'piece',
                'emoji' => '🍍',
                'cost_price' => 61.75,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 70,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRU-005',
                'name' => 'Papaya',
                'price' => 70,
                'category' => 'Fruits',
                'stock_quantity' => 26,
                'unit' => 'kg',
                'emoji' => '🍈',
                'cost_price' => 45.50,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 80,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'VEG-003',
                'name' => 'Pechay',
                'price' => 45,
                'category' => 'Vegetables',
                'stock_quantity' => 32,
                'unit' => 'bunch',
                'emoji' => '🥬',
                'cost_price' => 29.25,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 90,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'VEG-004',
                'name' => 'Eggplant',
                'price' => 80,
                'category' => 'Vegetables',
                'stock_quantity' => 25,
                'unit' => 'kg',
                'emoji' => '🍆',
                'cost_price' => 52,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 75,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'VEG-005',
                'name' => 'Red Onion',
                'price' => 140,
                'category' => 'Vegetables',
                'stock_quantity' => 22,
                'unit' => 'kg',
                'emoji' => '🧅',
                'cost_price' => 91,
                'reorder_level' => 7,
                'min_stock' => 4,
                'max_stock' => 65,
                'supplier_id' => $supplierIds['Manila Fresh Produce Co.'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PAN-002',
                'name' => 'Brown Rice',
                'price' => 72,
                'category' => 'Rice & Grains',
                'stock_quantity' => 65,
                'unit' => 'kg',
                'emoji' => '🌾',
                'cost_price' => 52,
                'reorder_level' => 18,
                'min_stock' => 10,
                'max_stock' => 180,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PAN-003',
                'name' => 'Rolled Oats',
                'price' => 115,
                'category' => 'Rice & Grains',
                'stock_quantity' => 36,
                'unit' => 'pack',
                'emoji' => '🥣',
                'cost_price' => 74.75,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 90,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PAN-004',
                'name' => 'Corn Grits',
                'price' => 68,
                'category' => 'Rice & Grains',
                'stock_quantity' => 48,
                'unit' => 'kg',
                'emoji' => '🌽',
                'cost_price' => 44.20,
                'reorder_level' => 12,
                'min_stock' => 6,
                'max_stock' => 120,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-001',
                'name' => 'Sardines in Tomato Sauce',
                'price' => 28,
                'category' => 'Canned Goods',
                'stock_quantity' => 84,
                'unit' => 'can',
                'emoji' => '🥫',
                'cost_price' => 18.20,
                'reorder_level' => 24,
                'min_stock' => 12,
                'max_stock' => 200,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-002',
                'name' => 'Corned Beef',
                'price' => 92,
                'category' => 'Canned Goods',
                'stock_quantity' => 54,
                'unit' => 'can',
                'emoji' => '🥫',
                'cost_price' => 59.80,
                'reorder_level' => 15,
                'min_stock' => 8,
                'max_stock' => 140,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-003',
                'name' => 'Tuna Flakes in Oil',
                'price' => 55,
                'category' => 'Canned Goods',
                'stock_quantity' => 60,
                'unit' => 'can',
                'emoji' => '🐟',
                'cost_price' => 35.75,
                'reorder_level' => 18,
                'min_stock' => 9,
                'max_stock' => 150,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-004',
                'name' => 'Coconut Milk',
                'price' => 48,
                'category' => 'Canned Goods',
                'stock_quantity' => 45,
                'unit' => 'can',
                'emoji' => '🥥',
                'cost_price' => 31.20,
                'reorder_level' => 12,
                'min_stock' => 6,
                'max_stock' => 120,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'SNK-001',
                'name' => 'Banana Chips',
                'price' => 75,
                'category' => 'Snacks',
                'stock_quantity' => 42,
                'unit' => 'pack',
                'emoji' => '🍌',
                'cost_price' => 48.75,
                'reorder_level' => 12,
                'min_stock' => 6,
                'max_stock' => 110,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'SNK-002',
                'name' => 'Salted Crackers',
                'price' => 58,
                'category' => 'Snacks',
                'stock_quantity' => 50,
                'unit' => 'pack',
                'emoji' => '🍘',
                'cost_price' => 37.70,
                'reorder_level' => 14,
                'min_stock' => 7,
                'max_stock' => 130,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'SNK-003',
                'name' => 'Cheese Corn Chips',
                'price' => 35,
                'category' => 'Snacks',
                'stock_quantity' => 68,
                'unit' => 'bag',
                'emoji' => '🧀',
                'cost_price' => 22.75,
                'reorder_level' => 20,
                'min_stock' => 10,
                'max_stock' => 170,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'SNK-004',
                'name' => 'Chocolate Wafer',
                'price' => 42,
                'category' => 'Snacks',
                'stock_quantity' => 56,
                'unit' => 'pack',
                'emoji' => '🍫',
                'cost_price' => 27.30,
                'reorder_level' => 16,
                'min_stock' => 8,
                'max_stock' => 140,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BEV-003',
                'name' => 'Instant Coffee',
                'price' => 165,
                'category' => 'Beverages',
                'stock_quantity' => 38,
                'unit' => 'pack',
                'emoji' => '☕',
                'cost_price' => 107.25,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 95,
                'supplier_id' => $supplierIds['Metro Beverage Distribution'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BEV-004',
                'name' => 'Powdered Chocolate Drink',
                'price' => 120,
                'category' => 'Beverages',
                'stock_quantity' => 40,
                'unit' => 'pack',
                'emoji' => '🍫',
                'cost_price' => 78,
                'reorder_level' => 12,
                'min_stock' => 6,
                'max_stock' => 100,
                'supplier_id' => $supplierIds['Metro Beverage Distribution'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BEV-005',
                'name' => 'Calamansi Juice',
                'price' => 85,
                'category' => 'Beverages',
                'stock_quantity' => 36,
                'unit' => 'bottle',
                'emoji' => '🧃',
                'cost_price' => 55.25,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 90,
                'supplier_id' => $supplierIds['Metro Beverage Distribution'],
                'status' => 'Active',
            ],
            [
                'sku' => 'DAI-001',
                'name' => 'Fresh Milk',
                'price' => 95,
                'category' => 'Dairy',
                'stock_quantity' => 30,
                'unit' => 'carton',
                'emoji' => '🥛',
                'cost_price' => 61.75,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 75,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'DAI-002',
                'name' => 'Evaporated Milk',
                'price' => 42,
                'category' => 'Dairy',
                'stock_quantity' => 55,
                'unit' => 'can',
                'emoji' => '🥛',
                'cost_price' => 27.30,
                'reorder_level' => 16,
                'min_stock' => 8,
                'max_stock' => 140,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'DAI-003',
                'name' => 'Cheddar Cheese',
                'price' => 145,
                'category' => 'Dairy',
                'stock_quantity' => 24,
                'unit' => 'pack',
                'emoji' => '🧀',
                'cost_price' => 94.25,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 60,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'DAI-004',
                'name' => 'Yogurt Drink',
                'price' => 38,
                'category' => 'Dairy',
                'stock_quantity' => 48,
                'unit' => 'bottle',
                'emoji' => '🥛',
                'cost_price' => 24.70,
                'reorder_level' => 14,
                'min_stock' => 7,
                'max_stock' => 120,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BAK-002',
                'name' => 'Pandesal Pack',
                'price' => 45,
                'category' => 'Bakery',
                'stock_quantity' => 35,
                'unit' => 'pack',
                'emoji' => '🥖',
                'cost_price' => 29.25,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 90,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BAK-003',
                'name' => 'Ensaymada',
                'price' => 38,
                'category' => 'Bakery',
                'stock_quantity' => 28,
                'unit' => 'piece',
                'emoji' => '🧁',
                'cost_price' => 24.70,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 70,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'BAK-004',
                'name' => 'Whole Wheat Bread',
                'price' => 72,
                'category' => 'Bakery',
                'stock_quantity' => 22,
                'unit' => 'loaf',
                'emoji' => '🍞',
                'cost_price' => 46.80,
                'reorder_level' => 7,
                'min_stock' => 4,
                'max_stock' => 60,
                'supplier_id' => $supplierIds['Luzon Pantry Supplies'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRZ-001',
                'name' => 'Chicken Hotdog',
                'price' => 135,
                'category' => 'Frozen Goods',
                'stock_quantity' => 28,
                'unit' => 'pack',
                'emoji' => '🌭',
                'cost_price' => 87.75,
                'reorder_level' => 9,
                'min_stock' => 5,
                'max_stock' => 70,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRZ-002',
                'name' => 'Pork Tocino',
                'price' => 185,
                'category' => 'Frozen Goods',
                'stock_quantity' => 20,
                'unit' => 'pack',
                'emoji' => '🥩',
                'cost_price' => 120.25,
                'reorder_level' => 7,
                'min_stock' => 4,
                'max_stock' => 55,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRZ-003',
                'name' => 'Frozen Mixed Vegetables',
                'price' => 110,
                'category' => 'Frozen Goods',
                'stock_quantity' => 26,
                'unit' => 'pack',
                'emoji' => '🥦',
                'cost_price' => 71.50,
                'reorder_level' => 8,
                'min_stock' => 4,
                'max_stock' => 65,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'FRZ-004',
                'name' => 'Vanilla Ice Cream',
                'price' => 175,
                'category' => 'Frozen Goods',
                'stock_quantity' => 18,
                'unit' => 'tub',
                'emoji' => '🍨',
                'cost_price' => 113.75,
                'reorder_level' => 6,
                'min_stock' => 3,
                'max_stock' => 48,
                'supplier_id' => $supplierIds['Southern Luzon Dairy & Frozen Foods'],
                'status' => 'Active',
            ],
            [
                'sku' => 'HSH-001',
                'name' => 'Dishwashing Liquid',
                'price' => 92,
                'category' => 'Household',
                'stock_quantity' => 40,
                'unit' => 'bottle',
                'emoji' => '🧴',
                'cost_price' => 59.80,
                'reorder_level' => 12,
                'min_stock' => 6,
                'max_stock' => 100,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'HSH-002',
                'name' => 'Laundry Detergent Powder',
                'price' => 145,
                'category' => 'Household',
                'stock_quantity' => 34,
                'unit' => 'pack',
                'emoji' => '🧺',
                'cost_price' => 94.25,
                'reorder_level' => 10,
                'min_stock' => 5,
                'max_stock' => 85,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'HSH-003',
                'name' => 'Kitchen Trash Bags',
                'price' => 85,
                'category' => 'Household',
                'stock_quantity' => 30,
                'unit' => 'roll',
                'emoji' => '🗑️',
                'cost_price' => 55.25,
                'reorder_level' => 9,
                'min_stock' => 5,
                'max_stock' => 75,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'HSH-004',
                'name' => 'Toilet Tissue 4-Roll',
                'price' => 78,
                'category' => 'Household',
                'stock_quantity' => 44,
                'unit' => 'pack',
                'emoji' => '🧻',
                'cost_price' => 50.70,
                'reorder_level' => 12,
                'min_stock' => 6,
                'max_stock' => 110,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PER-001',
                'name' => 'Bath Soap',
                'price' => 42,
                'category' => 'Personal Care',
                'stock_quantity' => 60,
                'unit' => 'bar',
                'emoji' => '🧼',
                'cost_price' => 27.30,
                'reorder_level' => 18,
                'min_stock' => 9,
                'max_stock' => 150,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PER-002',
                'name' => 'Shampoo Sachet Pack',
                'price' => 65,
                'category' => 'Personal Care',
                'stock_quantity' => 52,
                'unit' => 'pack',
                'emoji' => '🧴',
                'cost_price' => 42.25,
                'reorder_level' => 15,
                'min_stock' => 8,
                'max_stock' => 130,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PER-003',
                'name' => 'Toothpaste',
                'price' => 95,
                'category' => 'Personal Care',
                'stock_quantity' => 38,
                'unit' => 'tube',
                'emoji' => '🪥',
                'cost_price' => 61.75,
                'reorder_level' => 11,
                'min_stock' => 6,
                'max_stock' => 95,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'PER-004',
                'name' => 'Rubbing Alcohol',
                'price' => 75,
                'category' => 'Personal Care',
                'stock_quantity' => 46,
                'unit' => 'bottle',
                'emoji' => '🧴',
                'cost_price' => 48.75,
                'reorder_level' => 13,
                'min_stock' => 7,
                'max_stock' => 115,
                'supplier_id' => $supplierIds['Metro Household & Personal Care Supply'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-005',
                'name' => 'Soy Sauce',
                'price' => 28,
                'category' => 'Condiments',
                'stock_quantity' => 70,
                'unit' => 'bottle',
                'emoji' => '🧂',
                'cost_price' => 18.20,
                'reorder_level' => 20,
                'min_stock' => 10,
                'max_stock' => 180,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-006',
                'name' => 'Cane Vinegar',
                'price' => 25,
                'category' => 'Condiments',
                'stock_quantity' => 68,
                'unit' => 'bottle',
                'emoji' => '🧂',
                'cost_price' => 16.25,
                'reorder_level' => 20,
                'min_stock' => 10,
                'max_stock' => 170,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
            [
                'sku' => 'CND-007',
                'name' => 'Banana Ketchup',
                'price' => 55,
                'category' => 'Condiments',
                'stock_quantity' => 50,
                'unit' => 'bottle',
                'emoji' => '🍅',
                'cost_price' => 35.75,
                'reorder_level' => 15,
                'min_stock' => 8,
                'max_stock' => 130,
                'supplier_id' => $supplierIds['Philippine Grocery Brands Trading'],
                'status' => 'Active',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->updateOrInsert(
                ['sku' => $product['sku']],
                $product,
            );

            $productId = DB::table('products')
                ->where('sku', $product['sku'])
                ->value('id');
            DB::table('inventory_movements')->updateOrInsert(
                [
                    'product_id' => $productId,
                    'reference_id' => 'DEMO-INITIAL-STOCK',
                ],
                [
                    'sku' => $product['sku'],
                    'movement_type' => 'Stock In',
                    'quantity' => $product['stock_quantity'],
                    'previous_stock' => 0,
                    'new_stock' => $product['stock_quantity'],
                    'performed_by' => 'database-seeder',
                    'notes' => 'Initial stock from repeatable demo data seeder.',
                ],
            );
        }
    }

    private function seedAccounts(): void
    {
        $password = $this->demoPassword();
        $passwordHash = Hash::make($password);
        $roles = DB::table('roles')->pluck('id', 'name');
        $employeeId = DB::table('employees')
            ->where('employee_no', 'EMP-0001')
            ->value('id');
        $accounts = [
            ['username' => 'cashier', 'full_name' => 'Demo Cashier', 'role' => 'Cashier'],
            ['username' => 'hr', 'full_name' => 'Demo HR Manager', 'role' => 'HR Manager'],
            ['username' => 'finance', 'full_name' => 'Demo Finance Manager', 'role' => 'Finance Manager'],
            ['username' => 'operations', 'full_name' => 'Demo Operations Manager', 'role' => 'Operations Manager'],
            ['username' => 'inventory', 'full_name' => 'Demo Inventory Staff', 'role' => 'Inventory Staff'],
            [
                'username' => 'employee',
                'full_name' => 'Maria Santos',
                'role' => 'Employee',
                'employee_id' => $employeeId,
            ],
        ];

        foreach ($accounts as $account) {
            DB::table('admin_users')->updateOrInsert(
                ['username' => $account['username']],
                [
                    'password_hash' => $passwordHash,
                    'full_name' => $account['full_name'],
                    'role_id' => $roles[$account['role']],
                    'employee_id' => $account['employee_id'] ?? null,
                    'status' => 'Active',
                ],
            );
        }
    }

    private function seedAttendance(): void
    {
        $employeeIds = DB::table('employees')->pluck('id', 'employee_no');
        $entries = [
            ['employee_no' => 'EMP-0001', 'log_date' => '2026-07-27', 'time_in' => '08:02', 'time_out' => '17:05', 'status' => 'Present'],
            ['employee_no' => 'EMP-0001', 'log_date' => '2026-07-28', 'time_in' => '08:18', 'time_out' => '17:10', 'status' => 'Late'],
            ['employee_no' => 'EMP-0002', 'log_date' => '2026-07-27', 'time_in' => '07:55', 'time_out' => '17:00', 'status' => 'Present'],
            ['employee_no' => 'EMP-0003', 'log_date' => '2026-07-27', 'time_in' => '08:00', 'time_out' => '17:03', 'status' => 'Present'],
        ];

        foreach ($entries as $entry) {
            $employeeNo = $entry['employee_no'];
            unset($entry['employee_no']);
            $entry['employee_id'] = $employeeIds[$employeeNo];
            DB::table('attendance_logs')->updateOrInsert(
                [
                    'employee_id' => $entry['employee_id'],
                    'log_date' => $entry['log_date'],
                ],
                $entry,
            );
        }
    }

    private function seedRequestsAndPayroll(): void
    {
        $employeeIds = DB::table('employees')->pluck('id', 'employee_no');

        DB::table('hr_requests')->updateOrInsert(
            [
                'employee_id' => $employeeIds['EMP-0001'],
                'request_type' => 'Leave',
                'start_date' => '2026-08-10',
                'end_date' => '2026-08-11',
            ],
            [
                'hours' => null,
                'reason' => 'Family appointment',
                'status' => 'Pending',
            ],
        );

        DB::table('finance_requests')->updateOrInsert(
            [
                'employee_id' => $employeeIds['EMP-0001'],
                'request_type' => 'Reimbursement',
                'description' => 'Local delivery transport',
            ],
            [
                'amount' => 475.50,
                'category' => 'Transportation',
                'status' => 'Pending',
            ],
        );

        DB::table('payroll')->updateOrInsert(
            [
                'employee_id' => $employeeIds['EMP-0002'],
                'pay_period_start' => '2026-07-16',
                'pay_period_end' => '2026-07-31',
            ],
            [
                'basic_salary' => 15000,
                'hourly_rate' => 180,
                'regular_hours' => 80,
                'overtime_hours' => 2,
                'overtime_pay' => 450,
                'allowances' => 500,
                'bonuses' => 0,
                'deductions' => 750,
                'net_pay' => 15200,
                'status' => 'Draft',
                'created_by' => 'database-seeder',
                'pay_frequency' => 'Semi-monthly',
            ],
        );
    }

    private function demoPassword(): string
    {
        $password = env('FRESHMART_DEMO_PASSWORD');

        if (is_string($password) && trim($password) !== '') {
            return $password;
        }

        if (! app()->environment(['local', 'testing'])) {
            throw new RuntimeException(
                'FRESHMART_DEMO_PASSWORD must be set when demo seeding is enabled outside local or testing.',
            );
        }

        return 'test123';
    }
}
