<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../../api/http.js'
import { UiButton, UiErrorState, UiInput, UiPageHeader, UiSelect, UiStatusBadge, UiTableShell } from '../../components/ui/index.js'
import { formatMoney } from '../../utils/formatters.js'

const route = useRoute(); const payable = ref(null); const payments = ref([]); const loading = ref(true); const error = ref(''); const submitting = ref(false); const reviewMode = ref(false); const paymentAttemptKey = ref(null)
function localDate() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }
const paymentForm = ref({ amount: '', payment_method: 'Bank Transfer', reference_number: '', payment_date: localDate(), notes: '' })
const canRecord = computed(() => Number(payable.value?.outstanding_balance || 0) > 0)
function newIdempotencyKey() { return globalThis.crypto?.randomUUID?.() || `supplier-payment-${Date.now()}-${Math.random().toString(36).slice(2)}` }
function resetPaymentAttempt() { paymentAttemptKey.value = null; reviewMode.value = false; paymentForm.value = { amount: payable.value ? Number(payable.value.outstanding_balance).toFixed(2) : '', payment_method: 'Bank Transfer', reference_number: '', payment_date: localDate(), notes: '' } }
function leaveReview() { reviewMode.value = false }
async function load() { loading.value = true; error.value = ''; try { const [detail, history] = await Promise.all([api.get(`/accounts-payable/${route.params.payableId}`), api.get(`/accounts-payable/${route.params.payableId}/payments`)]); payable.value = detail.payable; payments.value = history.payments; if (!paymentForm.value.amount) paymentForm.value.amount = Number(payable.value.outstanding_balance).toFixed(2) } catch (requestError) { error.value = requestError.message } finally { loading.value = false } }
function reviewPayment() { error.value = ''; if (!canRecord.value || Number(paymentForm.value.amount) <= 0) { error.value = 'Enter a payment amount greater than zero.'; return }; if (Number(paymentForm.value.amount) > Number(payable.value.outstanding_balance)) { error.value = 'Payment amount exceeds the outstanding balance.'; return }; if (!paymentAttemptKey.value) paymentAttemptKey.value = newIdempotencyKey(); reviewMode.value = true }
async function confirmPayment() { if (!reviewMode.value || !paymentAttemptKey.value) return; submitting.value = true; error.value = ''; try { const result = await api.post(`/accounts-payable/${payable.value.id}/payments`, { ...paymentForm.value, amount: Number(paymentForm.value.amount), reference_number: paymentForm.value.reference_number.trim() || null, notes: paymentForm.value.notes.trim() || null, idempotency_key: paymentAttemptKey.value }); payable.value = result.payable; const history = await api.get(`/accounts-payable/${payable.value.id}/payments`); payments.value = history.payments; resetPaymentAttempt() } catch (requestError) { error.value = requestError.message } finally { submitting.value = false } }
function closeTone(status) { return status === 'Complete' ? 'success' : status === 'Open — Awaiting Delivery' ? 'info' : 'warning' }
watch(() => route.params.payableId, load); onMounted(load)
</script>
<template>
  <UiPageHeader title="Accounts Payable Detail" description="Review the payable, its procurement context, and supplier-payment settlement history." :breadcrumbs="[{ label: 'Accounts Payable', to: '/finance/accounts-payable' }, { label: payable ? `Payable #${payable.id}` : 'Payable detail' }]" />
  <UiErrorState v-if="error && !payable" :message="error" :retrying="loading" @retry="load" />
  <section v-else-if="loading" class="ui-card payable-panel">Loading accounts payable…</section>
  <template v-else-if="payable"><section class="ui-card payable-panel"><div><h2>{{ payable.supplier_name || 'Supplier not assigned' }}</h2><p>Payable #{{ payable.id }} · {{ payable.source === 'structured' ? 'Structured invoice' : 'Legacy payable' }}</p></div><UiStatusBadge :status="payable.status" /></section><section class="payable-metrics"><article class="ui-card"><span>Total amount</span><strong>{{ formatMoney(payable.total_amount) }}</strong></article><article class="ui-card"><span>Amount paid</span><strong>{{ formatMoney(payable.amount_paid) }}</strong></article><article class="ui-card"><span>Outstanding balance</span><strong>{{ formatMoney(payable.outstanding_balance) }}</strong></article><article class="ui-card"><span>Due date</span><strong>{{ payable.due_date || 'Not set' }}</strong></article></section><section class="ui-card payable-panel"><h2>Source and procurement context</h2><dl><dt>Purchase order</dt><dd>{{ payable.po_number || 'Not linked' }}</dd><dt>Invoice</dt><dd>{{ payable.invoice_number || 'Not linked' }}</dd><dt>Procurement close-out</dt><dd><UiStatusBadge :status="payable.procurement_close_status || 'Not available'" :tone="closeTone(payable.procurement_close_status)" /></dd></dl></section><p v-if="error" class="form-error" role="alert">{{ error }}</p>
    <section v-if="canRecord" class="ui-card payable-panel"><h2>Record supplier payment</h2><form v-if="!reviewMode" class="payment-form" @submit.prevent="reviewPayment"><UiInput v-model="paymentForm.amount" label="Payment amount" type="number" min="0.01" :max="payable.outstanding_balance" step=".01" required @update:model-value="leaveReview" /><UiSelect v-model="paymentForm.payment_method" label="Payment method" required @change="leaveReview"><option>Bank Transfer</option><option>Check</option><option>Cash</option><option>Other</option></UiSelect><UiInput v-model="paymentForm.reference_number" label="Reference number" maxlength="255" hint="Optional" @update:model-value="leaveReview" /><UiInput v-model="paymentForm.payment_date" label="Payment date" type="date" required @update:model-value="leaveReview" /><UiInput v-model="paymentForm.notes" label="Notes" maxlength="1000" hint="Optional" @update:model-value="leaveReview" /><div class="payment-actions"><UiButton type="submit">Review payment</UiButton><UiButton type="button" variant="secondary" @click="resetPaymentAttempt">Reset payment attempt</UiButton></div></form><div v-else class="payment-review"><h3>Review payment before recording</h3><dl><dt>Payable / supplier</dt><dd>Payable #{{ payable.id }} — {{ payable.supplier_name || 'Not assigned' }}</dd><dt>Amount</dt><dd>{{ formatMoney(paymentForm.amount) }}</dd><dt>Payment date</dt><dd>{{ paymentForm.payment_date }}</dd><dt>Payment method</dt><dd>{{ paymentForm.payment_method }}</dd><dt v-if="paymentForm.reference_number">Reference</dt><dd v-if="paymentForm.reference_number">{{ paymentForm.reference_number }}</dd></dl><div class="payment-actions"><UiButton variant="secondary" :disabled="submitting" @click="leaveReview">Back / edit</UiButton><UiButton :loading="submitting" @click="confirmPayment">Confirm and record payment</UiButton></div></div></section>
    <UiTableShell title="Supplier-payment history" :empty="!payments.length" empty-title="No supplier payments"><table><thead><tr><th>Payment date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Created by</th></tr></thead><tbody><tr v-for="payment in payments" :key="payment.id"><td>{{ payment.payment_date }}</td><td>{{ formatMoney(payment.amount) }}</td><td>{{ payment.payment_method }}</td><td>{{ payment.reference_number || '—' }}</td><td>{{ payment.created_by }}</td></tr></tbody></table></UiTableShell>
  </template>
</template>
<style scoped>.payable-panel{padding:1rem;margin-bottom:1rem}.payable-panel h2{margin-top:0}.payable-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.payable-metrics article{padding:1rem;display:grid;gap:.4rem}.payable-metrics strong{font-size:1.2rem}.payable-panel dl,.payment-review dl{display:grid;grid-template-columns:max-content 1fr;gap:.5rem 1rem;margin:0}.payable-panel dt,.payment-review dt{font-weight:700}.payable-panel dd,.payment-review dd{margin:0}.payment-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.payment-actions{display:flex;gap:.5rem;flex-wrap:wrap;grid-column:1/-1}.payment-review{display:grid;gap:1rem}@media(max-width:760px){.payable-metrics,.payment-form{grid-template-columns:1fr}}</style>
